version: '3.8'

services:
    db:
        image: postgres:17
        container_name: postgres_benchmark
        environment:
            POSTGRES_USER: benchmark_user
            POSTGRES_PASSWORD: benchmark_pass
            POSTGRES_DB: benchmark_db
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U benchmark_user"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    pgdata:
